# Generated by Django 6.0 on 2025-12-31 08:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Assessment instructions with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Course description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Module description with rich text formatting'),
        ),
    ]
