# Generated by Django 6.0 on 2026-01-02 05:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assessment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='text_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text content with rich text formatting (colors, paragraphs, styles)'),
        ),
    ]
