# Generated by Django 6.0 on 2026-01-02 06:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trainingmodule_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF file - uploads directly to Cloudinary', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='training/pdfs/%Y/%m/'),
        ),
    ]
