# Generated by Django 6.0 on 2026-01-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trainingmodule_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF file - uploads directly to Cloudinary', upload_to='training/pdfs/%Y/%m/'),
        ),
    ]
